@extends('layouts.app')
@section('title','Backlink manager & verification')
@section('description','Manage supplied backlink lists. Authority metrics and complete discovery require a separately configured data source.')
@section('action')<a class="btn" href="{{ route('seo.backlinks.export') }}">Export CSV</a>@endsection
@section('content')
<div class="grid gap-6 xl:grid-cols-2"><form class="card space-y-4" method="POST" action="{{ route('seo.backlinks.store') }}">@csrf<h2 class="font-semibold">Add backlink</h2><div><label class="label" for="project_id">Project</label><select class="input" name="project_id" id="project_id" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div>@foreach(['source_url'=>'Source URL','target_url'=>'Target URL','anchor'=>'Expected anchor (optional)','campaign'=>'Campaign (optional)'] as $key=>$label)<div><label class="label" for="{{ $key }}">{{ $label }}</label><input class="input" name="{{ $key }}" id="{{ $key }}" type="{{ str_ends_with($key,'url') ? 'url' : 'text' }}" @required(str_ends_with($key,'url')) maxlength="{{ $key==='anchor' ? 300 : ($key==='campaign' ? 150 : 2048) }}"></div>@endforeach<button class="btn">Save backlink</button></form>
<form class="card space-y-4" method="POST" enctype="multipart/form-data" action="{{ route('seo.backlinks.import') }}">@csrf<h2 class="font-semibold">Import backlink list</h2><div><label class="label" for="import_project">Project</label><select class="input" name="project_id" id="import_project" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div><label class="label" for="file">CSV (500 rows, 256 KB maximum)</label><input class="input" name="file" id="file" type="file" accept=".csv" required></div><p class="text-sm leading-6 text-gray-500">Required headers: source_url,target_url. Optional: anchor,campaign. Verification runs separately on the queue and respects robots.txt and access controls.</p><button class="btn-secondary">Import backlinks</button></form></div>
<div class="card mt-6"><form class="mb-4 flex flex-wrap gap-3"><input class="input max-w-xs" name="q" value="{{ request('q') }}" placeholder="Search source URLs" aria-label="Search source URLs"><select class="input w-auto" name="status" aria-label="Verification status"><option value="">All statuses</option>@foreach(['unverified','queued','found','not_found','failed'] as $status)<option @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><button class="btn-secondary">Filter</button></form><div class="overflow-x-auto"><table class="w-full"><thead><tr><th class="table-th">Source</th><th class="table-th">Target</th><th class="table-th">Project</th><th class="table-th">Campaign</th><th class="table-th">Status</th></tr></thead><tbody>@forelse($backlinks as $backlink)<tr><td class="table-td break-all"><a class="text-orange-600" href="{{ route('seo.backlinks.show',$backlink) }}">{{ $backlink->source_url }}</a></td><td class="table-td break-all">{{ $backlink->target_url }}</td><td class="table-td">{{ $backlink->project->name }}</td><td class="table-td">{{ $backlink->campaign ?? 'Not supplied' }}</td><td class="table-td"><span class="badge">{{ $backlink->status }}</span></td></tr>@empty<tr><td colspan="5" class="table-td">No supplied backlinks for your permitted projects.</td></tr>@endforelse</tbody></table></div>{{ $backlinks->links() }}</div>
@endsection
