@extends('layouts.app')
@section('title',$definition['name'])
@section('description',$definition['description'])
@section('action')<a class="btn-secondary" href="{{ route('seo.tools.index') }}">All SEO tools</a>@endsection
@section('content')
<form class="card max-w-3xl" method="POST" enctype="multipart/form-data" action="{{ route('seo.tools.run',$tool) }}" x-data="{ busy:false }" @submit="busy=true">@csrf
<div class="space-y-5"><div><label class="label" for="project_id">Project</label><select class="input" name="project_id" id="project_id">@can('clients.view')<option value="">Standalone analysis</option>@endcan @foreach($projects as $project)<option value="{{ $project->id }}" @selected(old('project_id',request('project_id'))==$project->id)>{{ $project->name }}</option>@endforeach</select></div>
@if($definition['mode']==='keywords')<div><label class="label" for="keywords">Keywords or seeds (one per line)</label><textarea class="input" name="keywords" id="keywords" rows="10" maxlength="100000" required>{{ old('keywords') }}</textarea><p class="mt-2 text-xs text-gray-400">Up to 500 keywords, each at most 200 characters. English-language intent rules; review suggestions before use.</p></div>@if($tool==='local-keywords')<div><label class="label" for="location">Location</label><input class="input" name="location" id="location" maxlength="100" required value="{{ old('location') }}"></div>@endif
@elseif($definition['mode']==='text')<div><label class="label" for="content">Content to analyze</label><textarea class="input" name="content" id="content" rows="12" maxlength="100000" required>{{ old('content') }}</textarea><p class="mt-2 text-xs text-gray-400">Plain text or HTML, up to 100,000 characters. Submitted HTML is analyzed and displayed as escaped text.</p></div><div><label class="label" for="keyword">Target keyword (optional)</label><input class="input" name="keyword" id="keyword" maxlength="200" value="{{ old('keyword') }}"></div>
@else<div><label class="label" for="url">URL</label><input class="input" type="url" name="url" id="url" required maxlength="2048" placeholder="https://example.com/" value="{{ old('url') }}"></div>@endif
</div><div class="mt-7 flex items-center gap-4"><button class="btn" :disabled="busy" x-text="busy ? 'Submitting…' : 'Run tool'">Run tool</button><p class="text-xs text-gray-400">Results are saved to your agency history.</p></div></form>
@if($definition['mode']==='network')<div class="card mt-6 max-w-3xl"><h2 class="font-semibold">Crawler safeguards</h2><p class="mt-3 text-sm leading-6 text-gray-500">Runs are queued. Public HTTP/HTTPS destinations only; robots.txt, configured delays, page limits, download limits and TLS verification apply. Pages blocked by access controls produce unverified errors. JavaScript-rendered content is not executed.</p></div>@endif
@endsection
