@extends('layouts.app')
@section('title',$definition['name'])
@section('description',$definition['description'])
@section('action')<a class="btn-secondary" href="{{ route('seo.tools.index') }}">All SEO tools</a>@endsection
@section('content')
@if($tool === 'audit')<div class="mb-5 max-w-3xl rounded-xl border border-orange-200 bg-orange-50 p-4 text-sm text-gray-700">Enter the website you want to check. Each submission starts a new audit and keeps your previous results in history.</div>@endif
<form class="card max-w-3xl" method="POST" enctype="multipart/form-data" action="{{ route('seo.tools.run',$tool) }}" x-data="{ busy:false }" @submit="busy=true">@csrf
<div class="space-y-5"><div><label class="label" for="project_id">Project</label><select class="input" name="project_id" id="project_id">@can('clients.view')<option value="">Standalone analysis</option>@endcan @foreach($projects as $project)<option value="{{ $project->id }}" @selected(old('project_id',request('project_id'))==$project->id)>{{ $project->name }}</option>@endforeach</select></div>
@if($definition['mode']==='keywords')<div><label class="label" for="keywords">Keywords or seeds (one per line)</label><textarea class="input" name="keywords" id="keywords" rows="10" maxlength="100000">{{ old('keywords') }}</textarea><p class="mt-2 text-xs text-gray-400">Up to 500 keywords, each at most 200 characters. English-language intent rules; review suggestions before use.</p><label class="label mt-4" for="file">Or import CSV/XLSX (first column, 256 KB maximum)</label><input class="input" name="file" id="file" type="file" accept=".csv,.xlsx"></div>@if($tool==='local-keywords')<div><label class="label" for="location">Location</label><input class="input" name="location" id="location" maxlength="100" required value="{{ old('location') }}"></div>@endif
@elseif($definition['mode']==='ai')<div class="rounded-lg bg-orange-50 p-4 text-sm leading-6 text-gray-600">AI suggestions require a configured provider and human review. Submitted context will be sent to DeepSeek when you run this tool. Normal tools work independently.</div><div><label class="label" for="content">Request and known facts</label><textarea class="input" name="content" id="content" rows="10" required maxlength="{{ \App\Services\AI\AIService::settings()['max_input_chars'] }}">{{ old('content') }}</textarea></div><div><label class="label" for="data_run_id">Collected findings (optional, same project)</label><select class="input" name="data_run_id" id="data_run_id"><option value="">Use supplied text only</option>@foreach($contextRuns as $contextRun)<option value="{{ $contextRun->id }}">Run #{{ $contextRun->id }} · {{ \App\Services\Seo\ToolRegistry::get($contextRun->tool)['name'] }} · {{ $contextRun->project_id ? 'Project #'.$contextRun->project_id : 'Standalone' }}</option>@endforeach</select></div>
@elseif($definition['mode']==='text')<div><label class="label" for="content">Content to analyze</label><textarea class="input" name="content" id="content" rows="12" maxlength="100000" required>{{ old('content') }}</textarea><p class="mt-2 text-xs text-gray-400">Plain text or HTML, up to 100,000 characters. Submitted HTML is analyzed and displayed as escaped text.</p></div><div><label class="label" for="keyword">Target keyword (optional)</label><input class="input" name="keyword" id="keyword" maxlength="200" value="{{ old('keyword') }}"></div>
@elseif($definition['mode']==='comparison')<div><label class="label" for="urls">Page URLs (your URL first, one per line)</label><textarea class="input" name="urls" id="urls" rows="6" maxlength="11000" required>{{ old('urls') }}</textarea><p class="mt-2 text-xs text-gray-400">Two to five URLs. Each permitted page is fetched and analyzed independently.</p></div>
@elseif($definition['mode']==='changes') @foreach(['before_run_id'=>'Before snapshot','after_run_id'=>'After snapshot'] as $key=>$label)<div><label class="label" for="{{ $key }}">{{ $label }}</label><select class="input" name="{{ $key }}" id="{{ $key }}" required>@foreach($contextRuns as $contextRun)<option value="{{ $contextRun->id }}">Run #{{ $contextRun->id }} · {{ $contextRun->tool }} · {{ $contextRun->project_id ? 'Project #'.$contextRun->project_id : 'Standalone' }}</option>@endforeach</select></div>@endforeach
@else<div><label class="label" for="url">URL</label><input class="input" type="url" name="url" id="url" required maxlength="2048" placeholder="https://example.com/" value="{{ old('url') }}"></div>@if($tool==='local-seo') @foreach(['business_name'=>'Business name','location'=>'Location','address'=>'Address (optional)','phone'=>'Phone (optional)'] as $key=>$label)<div><label class="label" for="{{ $key }}">{{ $label }}</label><input class="input" name="{{ $key }}" id="{{ $key }}" maxlength="{{ $key==='address' ? 300 : 200 }}" @required(in_array($key,['business_name','location'])) value="{{ old($key) }}"></div>@endforeach @endif @endif
@if($tool === 'audit')<div><label class="label" for="max_pages">Maximum pages to audit</label><input class="input" type="number" name="max_pages" id="max_pages" min="1" max="{{ \App\Services\Seo\ToolRegistry::settings()['max_pages'] }}" value="{{ old('max_pages', \App\Services\Seo\ToolRegistry::settings()['max_pages']) }}" required><p class="mt-2 text-xs text-gray-400">The crawl stops at this limit. Your plan may apply a lower limit.</p></div>@endif
</div><div class="mt-7 flex items-center gap-4"><button class="btn" :disabled="busy" x-text="busy ? 'Submitting…' : @js($tool === 'audit' ? 'Start website audit' : 'Run tool')">{{ $tool === 'audit' ? 'Start website audit' : 'Run tool' }}</button><p class="text-xs text-gray-400">Results are saved to your agency history.</p></div></form>
@if($definition['mode']==='network')<div class="card mt-6 max-w-3xl"><h2 class="font-semibold">Crawler safeguards</h2><p class="mt-3 text-sm leading-6 text-gray-500">Runs are queued. Public HTTP/HTTPS destinations only; robots.txt, configured delays, page limits, download limits and TLS verification apply. Pages blocked by access controls produce unverified errors. JavaScript-rendered content is not executed.</p></div>@endif
@endsection
