@extends('layouts.app')
@section('title',$keyword->keyword.' · Ranking history')
@section('description',$keyword->project->name.' · Observations are compared only within matching country, location, device and search engine.')
@section('action')<a class="btn-secondary" href="{{ route('seo.rankings.index') }}">All keywords</a>@endsection
@section('content')
<div class="mb-6 grid gap-4 sm:grid-cols-3 xl:grid-cols-5">@foreach(['Current'=>$current,'Previous'=>$previous,'Change'=>$change,'Best'=>$best,'Worst'=>$worst] as $label=>$value)<div class="card"><p class="text-xs text-gray-500">{{ $label }}</p><p class="mt-3 text-2xl font-semibold">{{ $value ?? 'Not available' }}</p></div>@endforeach</div>
<form class="card mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach($context as $key=>$value)<div><label class="label" for="filter-{{ $key }}">{{ ucwords(str_replace('_',' ',$key)) }}</label>@if($key==='device')<select class="input" name="device" id="filter-device">@foreach(['desktop','mobile','tablet'] as $device)<option @selected($value===$device)>{{ $device }}</option>@endforeach</select>@else<input class="input" name="{{ $key }}" id="filter-{{ $key }}" value="{{ $value }}" maxlength="{{ $key==='country' ? 2 : 100 }}">@endif</div>@endforeach<div class="self-end"><button class="btn-secondary">View context</button></div></form>
@if(count($history))<div class="card mb-6"><h2 class="mb-5 font-semibold">Position history · last 180 observations</h2><div class="h-64"><canvas data-ranking-history="{{ json_encode($history) }}" aria-label="Position history chart"></canvas></div><p class="mt-4 text-xs text-gray-400">Lower positions are better. Gaps represent observations without a known position.</p></div>@endif
<form class="card mb-6" method="POST" action="{{ route('seo.rankings.entry',$keyword) }}">@csrf<h2 class="mb-5 font-semibold">Record manual observation</h2><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div><label class="label" for="observed_on">Observed date</label><input class="input" type="date" name="observed_on" id="observed_on" max="{{ now()->toDateString() }}" value="{{ now()->toDateString() }}" required></div><div><label class="label" for="position">Position (blank = not found)</label><input class="input" type="number" min="1" max="1000" name="position" id="position"></div>@foreach($context as $key=>$value)<div><label class="label" for="entry-{{ $key }}">{{ ucwords(str_replace('_',' ',$key)) }}</label>@if($key==='device')<select class="input" name="device" id="entry-device">@foreach(['desktop','mobile','tablet'] as $device)<option @selected($value===$device)>{{ $device }}</option>@endforeach</select>@else<input class="input" name="{{ $key }}" id="entry-{{ $key }}" maxlength="{{ $key==='country' ? 2 : 100 }}" value="{{ $value }}" @required($key!=='location')>@endif</div>@endforeach<div class="sm:col-span-2"><label class="label" for="evidence">Evidence or observed range</label><input class="input" name="evidence" id="evidence" maxlength="2048"></div></div><button class="btn mt-5">Save manual observation</button></form>
<div class="card overflow-x-auto"><table class="w-full"><thead><tr><th class="table-th">Date</th><th class="table-th">Position</th><th class="table-th">Source</th><th class="table-th">Evidence</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td class="table-td">{{ $entry->observed_on->format('d M Y') }}</td><td class="table-td">{{ $entry->position ?? 'Not found in observed range' }}</td><td class="table-td">{{ $entry->source }}</td><td class="table-td">{{ $entry->evidence ?? 'Not supplied' }}</td></tr>@empty<tr><td colspan="4" class="table-td">No observations for this context. Manual input or import required.</td></tr>@endforelse</tbody></table>{{ $entries->links() }}</div>
@endsection
