@extends('layouts.app')
@section('title','Rank tracker & ranking report')
@section('description','Verified manual observations or CSV imports. No automated search-engine positions are claimed.')
@section('action')<a class="btn" href="{{ route('seo.rankings.export') }}">Export observations CSV</a>@endsection
@section('content')
<div class="grid gap-6 xl:grid-cols-2"><form class="card space-y-4" method="POST" action="{{ route('seo.rankings.store') }}">@csrf<h2 class="font-semibold">Add project keyword</h2><div><label class="label" for="project_id">Project</label><select class="input" name="project_id" id="project_id" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div><label class="label" for="keyword">Keyword</label><input class="input" name="keyword" id="keyword" maxlength="200" required></div><div><label class="label" for="target_url">Target URL (optional)</label><input class="input" type="url" name="target_url" id="target_url" maxlength="2048"></div><button class="btn">Save keyword</button></form>
<form class="card space-y-4" method="POST" enctype="multipart/form-data" action="{{ route('seo.rankings.import') }}">@csrf<h2 class="font-semibold">Import observations</h2><div><label class="label" for="import_project">Project</label><select class="input" name="project_id" id="import_project" required>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div><label class="label" for="file">CSV file (500 observations, 256 KB maximum)</label><input class="input" type="file" name="file" id="file" accept=".csv" required></div><p class="break-all text-xs leading-6 text-gray-500">Headers: keyword,observed_on,position,country,location,device,search_engine. Date: YYYY-MM-DD. Country: two letters. Device: desktop/mobile/tablet. Blank position means not found in the observed range. An optional evidence column can describe that range.</p><button class="btn-secondary">Import CSV</button></form></div>
<div class="card mt-6"><form class="mb-5 flex flex-wrap gap-3"><input class="input max-w-xs" name="q" placeholder="Search keywords" aria-label="Search keywords" value="{{ request('q') }}"><button class="btn-secondary">Filter</button></form><div class="overflow-x-auto"><table class="w-full"><thead><tr><th class="table-th">Keyword</th><th class="table-th">Project</th><th class="table-th">Observations</th><th class="table-th">Target URL</th></tr></thead><tbody>@forelse($keywords as $keyword)<tr><td class="table-td"><a class="text-orange-600" href="{{ route('seo.rankings.show',$keyword) }}">{{ $keyword->keyword }}</a></td><td class="table-td">{{ $keyword->project->name }}</td><td class="table-td">{{ $keyword->entries_count ?: 'Manual input or import required' }}</td><td class="table-td break-all">{{ $keyword->target_url ?? 'Not available' }}</td></tr>@empty<tr><td class="table-td" colspan="4">No keywords saved for your permitted projects.</td></tr>@endforelse</tbody></table></div>{{ $keywords->links() }}</div>
@endsection
