@extends('layouts.app')
@section('title','SEO engine settings')
@section('description','Configure crawler safeguards, diagnostic scoring, feature availability and agency limits.')
@section('content')
<form class="card space-y-7" method="POST" action="{{ route('seo.settings') }}">@csrf @method('PATCH')
<div><h2 class="mb-4 font-semibold">Crawler and execution limits</h2><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@foreach($engine as $key=>$value)<div><label class="label" for="engine-{{ $key }}">{{ ucwords(str_replace('_',' ',$key)) }}</label><input class="input" type="number" name="engine[{{ $key }}]" id="engine-{{ $key }}" value="{{ old('engine.'.$key,$value) }}" required></div>@endforeach</div></div>
<div><h2 class="mb-4 font-semibold">Score category weights</h2><p class="mb-4 text-sm text-gray-500">Relative weights are normalized for applicable categories. This score is an internal diagnostic, not a Google score.</p><div class="grid gap-4 sm:grid-cols-3">@foreach($weights as $key=>$value)<div><label class="label" for="weight-{{ $key }}">{{ ucwords(str_replace('_',' ',$key)) }}</label><input class="input" type="number" min="0" max="100" name="weights[{{ $key }}]" id="weight-{{ $key }}" value="{{ old('weights.'.$key,$value) }}" required></div>@endforeach</div></div>
<div><h2 class="mb-4 font-semibold">Disabled tools</h2><div class="grid gap-3 sm:grid-cols-2">@foreach($tools as $key=>$tool)<label class="flex items-center gap-3 text-sm"><input type="checkbox" name="disabled[]" value="{{ $key }}" @checked(in_array($key,old('disabled',$disabled),true))>{{ $tool['name'] }}</label>@endforeach</div></div><button class="btn">Save engine settings</button></form>
<form class="card mt-6" method="POST" action="{{ route('seo.settings.limit') }}">@csrf<h2 class="mb-5 font-semibold">Agency tool limits</h2><div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="agency_id">Agency</label><select class="input" name="agency_id" id="agency_id" required>@foreach($agencies as $agency)<option value="{{ $agency->id }}">{{ $agency->name }}</option>@endforeach</select></div><div><label class="label" for="tool">Tool</label><select class="input" name="tool" id="tool">@foreach($tools as $key=>$tool)<option value="{{ $key }}">{{ $tool['name'] }}</option>@endforeach</select></div><div><label class="label" for="monthly_runs">Monthly runs (blank means unlimited)</label><input class="input" type="number" min="0" max="1000000" name="monthly_runs" id="monthly_runs"></div><div><label class="label" for="enabled">Access</label><select class="input" name="enabled" id="enabled"><option value="1">Enabled</option><option value="0">Disabled</option></select></div></div><button class="btn mt-5">Save agency limit</button></form>
<div class="card mt-6 overflow-x-auto"><table class="w-full"><thead><tr><th class="table-th">Agency</th><th class="table-th">Tool</th><th class="table-th">Monthly limit</th><th class="table-th">Enabled</th></tr></thead><tbody>@forelse($limits as $limit)<tr><td class="table-td">{{ $limit->name }}</td><td class="table-td">{{ $tools[$limit->tool]['name'] ?? $limit->tool }}</td><td class="table-td">{{ $limit->monthly_runs ?? 'Unlimited' }}</td><td class="table-td">{{ $limit->enabled ? 'Yes' : 'No' }}</td></tr>@empty<tr><td colspan="4" class="table-td">No agency overrides configured.</td></tr>@endforelse</tbody></table>{{ $limits->links() }}</div>
@endsection
