@extends('layouts.app')
@section('title', 'Platform overview')
@section('description', 'Manage agencies and monitor real platform activity.')
@section('action')<a class="btn-secondary" href="{{ route('expiry.settings') }}">Configure expiry rules</a>@endsection
@section('content')
<div class="mb-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach($counts as $label => $value)<div class="card"><p class="text-sm text-gray-500">{{ $label }}</p><p class="mt-4 text-4xl font-semibold">{{ number_format($value) }}</p></div>@endforeach</div>
<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div class="flex flex-wrap justify-between gap-4 p-6"><h2 class="text-lg font-semibold">Agencies</h2><form class="flex flex-wrap gap-2"><input class="input w-56" name="q" value="{{ request('q') }}" placeholder="Search agencies" aria-label="Search agencies"><select class="input w-auto" name="status" aria-label="Status"><option value="">All statuses</option>@foreach(['active','suspended'] as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="btn-secondary">Filter</button></form></div>
<div class="overflow-x-auto"><table class="w-full"><thead><tr>@foreach(['Agency','Team','Created','Status','Action'] as $head)<th class="table-th">{{ $head }}</th>@endforeach</tr></thead><tbody>@forelse($agencies as $agency)<tr><td class="table-td font-semibold">{{ $agency->name }}</td><td class="table-td">{{ $agency->users_count }}</td><td class="table-td">{{ $agency->created_at->format('d M Y') }}</td><td class="table-td"><span class="badge">{{ ucfirst($agency->status) }}</span></td><td class="table-td"><form method="POST" action="{{ route('super-admin.agency-status', $agency) }}" @submit="if (!confirm('Change access for this agency?')) $event.preventDefault()">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $agency->status === 'active' ? 'suspended' : 'active' }}"><button class="btn-secondary">{{ $agency->status === 'active' ? 'Suspend' : 'Reactivate' }}</button></form></td></tr>@empty<tr><td colspan="5" class="table-td py-14 text-center text-gray-400">No agencies found. Agencies appear when an owner registers.</td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $agencies->links() }}</div></div>
@endsection
