@extends('layouts.app')
@section('title',($subscription->client?->name ?? 'Archived client').' · SEO subscription')
@section('description','Manage this client’s service period and renewal history.')
@section('action')<a class="btn-secondary" href="{{ route('client-subscriptions.index') }}">Back to subscriptions</a>@endsection
@section('content')
<div class="grid gap-6 xl:grid-cols-3"><div class="space-y-6"><div class="card"><p class="text-xs font-medium uppercase tracking-widest text-gray-400">SEO plan</p><h2 class="mt-3 text-2xl font-semibold">{{ $subscription->plan->name }}</h2><span class="badge mt-3">{{ ucwords(str_replace('_',' ',$subscription->effectiveStatus())) }}</span><p class="mt-6 text-4xl font-semibold">{{ max(0,$subscription->remainingDays()) }} <span class="text-base font-normal text-gray-500">days remaining</span></p>@if($subscription->remainingDays()>0 && $subscription->remainingDays()<3)<p class="mt-2 text-sm text-orange-600">{{ now()->diffForHumans($subscription->expires_at,['parts'=>2,'syntax'=>\Carbon\CarbonInterface::DIFF_ABSOLUTE]) }} remaining</p>@endif
<div class="mt-6 h-2 overflow-hidden rounded-full bg-gray-100" role="progressbar" aria-label="Service period elapsed" aria-valuenow="{{ $subscription->progress() }}" aria-valuemin="0" aria-valuemax="100"><div class="h-full rounded-full bg-orange-500" style="width:{{ $subscription->progress() }}%"></div></div><div class="mt-3 flex justify-between text-xs text-gray-400"><span>{{ $subscription->starts_at->timezone(app(\App\Tenancy\TenantContext::class)->agency()->timezone)->format('d M Y') }}</span><span>{{ $subscription->expires_at->timezone(app(\App\Tenancy\TenantContext::class)->agency()->timezone)->format('d M Y') }}</span></div><dl class="mt-6 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-gray-400">Price</dt><dd>{{ $subscription->plan->currency }} {{ number_format($subscription->plan->price_minor/100,2) }}</dd></div><div class="flex justify-between"><dt class="text-gray-400">Billing cycle</dt><dd>{{ ucfirst($subscription->plan->billing_cycle) }}</dd></div><div class="flex justify-between"><dt class="text-gray-400">Grace period</dt><dd>{{ $subscription->grace_days }} days</dd></div><div class="flex justify-between"><dt class="text-gray-400">Expiry behavior</dt><dd>{{ ucwords(str_replace('_',' ',$subscription->expiry_mode)) }}</dd></div></dl></div>
@can('subscriptions.renew')<form class="card" method="POST" action="{{ route('client-subscriptions.renew',$subscription) }}" x-data="{ saving:false }" @submit="saving=true">@csrf<h2 class="mb-3 font-semibold">Renew service</h2><p class="mb-4 text-sm text-gray-500">Extend by {{ $subscription->plan->duration_days }} days and issue a new invoice. No automatic payment is collected.</p><label class="label" for="renew_reason">Renewal reason</label><input class="input" id="renew_reason" name="reason" required maxlength="2000"><button class="btn mt-4 w-full" :disabled="saving" x-text="saving ? 'Renewing…' : 'Renew subscription'">Renew subscription</button></form>@endcan
</div><div class="space-y-6 xl:col-span-2"><div class="card"><h2 class="mb-5 font-semibold">Invoices</h2><div class="overflow-x-auto"><table class="w-full"><thead><tr>@foreach(['Invoice','Amount','Status'] as $head)<th class="table-th">{{ $head }}</th>@endforeach</tr></thead><tbody>@forelse($invoices as $invoice)<tr><td class="table-td"><a class="text-orange-600" href="{{ route('invoices.show',$invoice) }}">{{ $invoice->number }}</a></td><td class="table-td">{{ $invoice->currency }} {{ number_format($invoice->amount_minor/100,2) }}</td><td class="table-td">{{ ucfirst(str_replace('_',' ',$invoice->status)) }}</td></tr>@empty<tr><td class="table-td" colspan="3">No invoices.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $invoices->links() }}</div></div>
@can('subscriptions.manage')<form class="card" method="POST" action="{{ route('client-subscriptions.change',$subscription) }}" x-data="{ action:'extend' }" @submit="if (!confirm('Apply this subscription change?')) $event.preventDefault()">@csrf @method('PATCH')<h2 class="mb-5 font-semibold">Change service period</h2><div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="action">Action</label><select class="input" name="action" id="action" x-model="action">@foreach(['extend','plan_change','cancel','suspend','reactivate'] as $action)<option value="{{ $action }}">{{ ucwords(str_replace('_',' ',$action)) }}</option>@endforeach</select></div><div x-show="action==='extend'"><label class="label" for="days">Days to extend</label><input class="input" id="days" name="days" type="number" min="1" max="3650" :disabled="action!=='extend'" :required="action==='extend'"></div><div x-cloak x-show="action==='plan_change'"><label class="label" for="new_plan">New SEO plan</label><select class="input" id="new_plan" name="client_plan_id" :disabled="action!=='plan_change'">@foreach(\App\Models\ClientPlan::where('is_active',true)->get() as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></div><div class="sm:col-span-2"><label class="label" for="reason">Reason</label><textarea class="input" id="reason" name="reason" required maxlength="2000"></textarea></div></div><button class="btn-secondary mt-5">Apply change</button></form>@endcan
<div class="card"><h2 class="mb-5 font-semibold">Subscription history</h2>@foreach($history as $event)<div class="border-t border-gray-100 py-4"><p class="text-sm font-semibold">{{ ucwords(str_replace('_',' ',$event->action)) }}</p><p class="mt-1 text-sm text-gray-500">{{ $event->reason }}</p><p class="mt-2 text-xs text-gray-400">{{ $event->user?->name ?? 'System' }} · {{ $event->created_at->format('d M Y H:i') }}</p></div>@endforeach<div class="mt-4">{{ $history->links() }}</div></div></div></div>
@endsection
